### ISSUE TITLE
Нужно уточнить README.md

### ISSUE THREAD

**Issue by Mazdaywik** [masyagin1998/HSV#1]
В `README.md` сказано:
> Для сборки и запуска библиотеки **HSV** необходим любой  `С99`-совместимый компилятор и утилита [Make](https://www.gnu.org/software/make/).
Библиотека **HSV** может быть легко перенесена на [C89](https://en.cppreference.com/), для этого необходимо лишь реализвовать некоторые библиотечные функции [<math.h>](https://www.gnu.org/software/libc/manual/html_node/Mathematics.html), добавленные в стандарте `C99`. Обратная совместимость обеспечивается объявлением всех переменных строго в начале блоков и использованием только "классических" типов данных.

И это неправда. Вернее, правда, но не полная. Компилятор MinGW GCC совместим с C99, и содержит утилиту Make. Но сборка не работает:
```
D:\…\HSV>mingw32-make.exe
Не найден файл: *.c
Не найден файл: *.c
Не найден файл: *.c
Не найден файл: *.c
Не найден файл: *.c
Не найден файл: *.c
mkdir -p .libs/
Ошибка в синтаксисе команды.
Makefile:107: recipe for target '.libs/hsv.a' failed
mingw32-make: *** [.libs/hsv.a] Error 1
```
Так что нужно уточнить, что библиотека ориентирована на unix-like системы.

**Comment by masyagin1998** [comment]
Да, согласен, спасибо!

**Comment by masyagin1998** [comment]
"Для сборки и запуска библиотеки HSV необходимы С99-совместимый компилятор, утилита Make и unix-совместимая ОС." - поправил Readme.

Ещё раз спасибо!
